# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import videos.models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180409_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=videos.models.upload_location),
        ),
    ]
