# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20180410_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoviews',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
